config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create] do
    post 'logout', on: :collection
  end

  resources :topics, only: [:index, :create, :destroy]

  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def create
    Topic.create(topic_params)
    redirect_to root_path
  end

  def destroy
    Topic.delete params[:id]
    redirect_to root_path
  end

  private
  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    username = params[:user][:username]
    session[:current_username] = username
    user = User.new username: username
    if not user.valid?
      raise "Oops"
    end
    # don't bother with DB

    redirect_to root_path
  end

  def logout
    session.delete :current_username
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    session[:current_username]
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Democracy3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<hr>
<%= render 'shared/stub_login' %>

</body>
</html>

app/views/shared/_stub_login.html.erb
<p>
<% if current_user %>
  You are <%= current_user %>. <%= link_to "Logout?", logout_users_path, method: :post %>
<% end %>
</p>

<header>Username</header>
<%= form_for :user, url: users_path do |f| %>
  <% f.text_field :username %>
<% end %>

app/views/topics/index.html.erb
<h1>All voting topics</h1>

<ul>
  <% @topics.each do |t| %>
    <li>
      <%= t.title %>
      <%= link_to "[x]", topic_path(t), method: :delete %>
    </li>
  <% end %>
</ul>

<%= form_for :topic do |f| %>
  <%= f.text_field :title %>
<% end %>